/*
 * This source file was generated by the Gradle 'init' task
 */
package org.chessgame;

import org.chessgame.model.PieceType;

public class ChessApplication {
    public static void main(String[] args) {
        if (args.length != 2) {
            System.out.println("Usage: java ChessApplication <pieceType> <position>");
            System.out.println("Example: java ChessApplication King D5");
            return;
        }

        String pieceType = args[0];
        String position = args[1].toUpperCase();
        PieceType type = PieceType.valueOf(pieceType.toUpperCase());
    }
}
